### ISSUE TITLE
Nothing in Internet Explorer (11)

### ISSUE THREAD

**Issue by lukmarcus** [wise-team/steem-wise-voter-page#17]
Page doesn't work in Internet Explorer 11... Nothing opens and source is:

```<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Wise Voter Page</title>
</head>
<body>
    <div id="app"></div>
</body>

<script src="./dist/build.js"></script>

</html>```

**Comment by Jblew** [comment]
I've probably fixed this in https://github.com/noisy-witness/steem-wise-voter-page/commit/254310b7e08f012b10bd7b3bb4ae842c660a9cab . Probably this was only a mistake in the structure of index.html file (Nov I've also added an anti-caching mechanism to webpack build :)). I don't have an ability to test The IE 11. But it seems to work on Microsoft Edge 17:
<img width="1440" alt="zrzut ekranu 2018-08-07 o 12 53 28" src="https://user-images.githubusercontent.com/776705/43772241-c0403450-9a41-11e8-84b4-9c72d7f0764c.png">

**Comment by Jblew** [comment]
@lukmarcus Can you tell me, do you get the same error?

<img width="1194" alt="zrzut ekranu 2018-08-07 o 13 04 45" src="https://user-images.githubusercontent.com/776705/43772469-8ba88b38-9a42-11e8-8cef-4047c968c58f.png">

**Comment by Jblew** [comment]
No reactions. Closing for now.
