### ISSUE TITLE
Wise works or not? Status will help

### ISSUE THREAD

**Issue by lukmarcus** [wise-team/steem-wise-voter-page#18]
It would be nice to know right from the start if Wise is working or not. Maybe a little status information at the top will help?

![wise_offline.png](https://cdn.steemitimages.com/DQmWxysFvPxCifFEdV3RJLiGU8gjdYNFqYtr5hW92oJ78Ka/wise_offline.png)

![wise_online.png](https://cdn.steemitimages.com/DQmbxCUzHajGdzigRumiw9c5WVYG8q82wyoGAVjcXNzJDTC/wise_online.png)

**Comment by Jblew** [comment]
Wise does not have any centralised server, so this is not possible. It depends on the status of each delegator's daemon.
Status will be possible only for the Wise portal when it will be available.
