### ISSUE TITLE
SteemConnect error in voter page (sc2-sdk error + Network request failed)

### ISSUE THREAD

**Issue by noisy** [wise-team/steem-wise-voter-page#39]
Earlier I often got message like this, but after another log in
![selection_999 164](https://user-images.githubusercontent.com/201263/45937020-05b0d800-bfbd-11e8-8543-eecfe0d86a3d.png)

error was disappearing.

Some useres suggest, that it happes for them once a while (access token is out of date?)

but latelly I also got this error:
![selection_999 182](https://user-images.githubusercontent.com/201263/45937041-38f36700-bfbd-11e8-8b2d-973c3b21cc7c.png)

![selection_999 184](https://user-images.githubusercontent.com/201263/45937047-490b4680-bfbd-11e8-9b84-b12c2ead2b2e.png)

**Comment by Jblew** [comment]
Fixed. closing.
