### ISSUE TITLE
Unable to load https://wise.vote/voting-page/

### ISSUE THREAD

**Issue by noisy** [wise-team/steem-wise-voter-page#44]
#### The problem: 

Page https://wise.vote/voting-page/ does not open:

![selection_999 696](https://user-images.githubusercontent.com/201263/50045510-720b1700-0094-11e9-8b20-02ae8d6fd5ac.png)

#### I did:

1. Open https://wise.vote/voting-page/

#### I expected to see:

Voting page should load

#### Instead, I saw:

> Refused to execute script from 'https://wise.vote/dist/build.js?0178262b40d28090ede6' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Additional info:
- clearing cache and localstorage doesn't help
- private mode in browser doesn't help
- Browser: Chrome Version 67.0.3396.87 (Official Build) (64-bit), Ubuntu
- I reproduced that on wise-test1, wise-test2, wise-test3 accounts
  - earlier I created for each of those accounts separate Google Chrome Profile... earlier it worked. Today I couldn't open this page on any Google Chrome Profile which belongs to any of those users.

**Comment by Jblew** [comment]
Most probably related to http-server pkg. Best fix is to create a multi stage build with nginx and include mime.types
