### ISSUE TITLE
No images on staging voting page

### ISSUE THREAD

**Issue by noisy** [wise-team/steem-wise-voter-page#45]
#### The problem: 

Currently, there is a problem with images on https://dev.wise.jblew.pl/voting-page/

![selection_999 726](https://user-images.githubusercontent.com/201263/50285929-fdeabd80-045d-11e9-9feb-3e22e0a88117.png)

![selection_999 727](https://user-images.githubusercontent.com/201263/50285925-fb886380-045d-11e9-9650-c91afabf95d5.png)

#### I expect to see

Voting page on staging should look like voting page on production

![screencapture-wise-vote-voting-page-2018-12-20-13_52_22](https://user-images.githubusercontent.com/201263/50286097-984b0100-045e-11e9-9cf6-5bb6f8fcfebe.png)

**Comment by noisy** [comment]
@Jblew is this a "staging only" issue or  is it actually a bug, which should be fixed before we deploy curent staging to production?

**Comment by Jblew** [comment]
This was because the fix for assets was done on master and not merged to staging. Now it is merged and images works on both
